# ingress:
#   enabled: false
#   # className: nginx
#   className: traefik
#   annotations:
#     {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: k8s.ki.fh-swf.de
#       paths:
#         - path: /gitea
#           pathType: Prefix
deployment:
  env:
    - name: "GITEA__server__ROOT_URL"
      value: "http://localhost:3000"
    # - name: VARIABLE
    #   value: my-value
gitea:
  ## @param gitea.admin.username Username for the Gitea admin user
  ## @param gitea.admin.existingSecret Use an existing secret to store admin user credentials
  ## @param gitea.admin.password Password for the Gitea admin user
  ## @param gitea.admin.email Email for the Gitea admin user
  ## @param gitea.admin.passwordMode Mode for how to set/update the admin user password. Options are: initialOnlyNoReset, initialOnlyRequireReset, and keepUpdated
  admin:
    # existingSecret: gitea-admin-secret
    existingSecret:
    username: gitea_admin2
    password: r8sA8CPHD9!bt6d
    email: "gitea2@local.domain"
    passwordMode: initialOnlyNoReset
strategy:
  type: "RollingUpdate"
  rollingUpdate:
    maxSurge: "100%"
    maxUnavailable: "100%"